### ISSUE TITLE
zustre error "cos function"

### ISSUE THREAD

**Issue by hbourbouh** [coco-team/zustre#5]
$ **/home/bourbouh/Documents/coco-team/cocoSim/tools/verifiers/linux/bin/zustre "/home/bourbouh/Documents/coco-team/benchmarks/Simulink/tcm/with_properties/lustre_files/src_AutoThrottle_Guide_100/AutoThrottle_Guide_100.lus" --node AutoThrottle_Guide_100_Guide_100 --xml --cg --matlab --timeout 60 --save** 
(error "line 277 column 60: Wrong number of arguments (2) passed to function (declare-fun cos (Real) Real)")
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bourbouh/Documents/coco-team/cocoSim/tools/verifiers/linux/bin/zustre", line 78, in main
    zus.encodeAndSolve()
  File "/home/bourbouh/Documents/coco-team/cocoSim/tools/verifiers/linux/lib/zustrepy/src/zustre.py", line 180, in encodeAndSolve
    q = self.fp.parse_file (hornFormulas)
  File "src/api/python/z3.py", line 6444, in parse_file
  File "src/api/python/z3core.py", line 4734, in Z3_fixedpoint_from_file
Z3Exception: parser error

[AutoThrottle_Guide_100.txt](https://github.com/coco-team/zustre/files/759211/AutoThrottle_Guide_100.txt)

**Comment by lememta** [comment]
I will close this issue.
