### ISSUE TITLE
cos and sim in smt2

### ISSUE THREAD

**Issue by hbourbouh** [coco-team/zustre#7]
**/home/bourbouh/Documents/coco-team/cocoSim/tools/verifiers/linux/bin/zustre "/home/bourbouh/Documents/coco-team/benchmarks/Simulink/tcm/with_properties/lustre_files/src_AutoThrottle_Guide_100/AutoThrottle_Guide_100.lus" --node AutoThrottle_Guide_100_Guide_100 --xml --cg --matlab --timeout 60 --save** 
(error "line 84 column 28: invalid declaration, builtin symbol sin")
(error "line 116 column 20: Wrong number of arguments (2) passed to function (declare-fun sin (Real) Real)")
(error "line 298 column 28: invalid declaration, builtin symbol cos")
(error "line 301 column 23: Wrong number of arguments (2) passed to function (declare-fun sin (Real) Real)")
(error "line 453 column 60: Wrong number of arguments (2) passed to function (declare-fun cos (Real) Real)")
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bourbouh/Documents/coco-team/cocoSim/tools/verifiers/linux/bin/zustre", line 76, in main
    zus.encodeAndSolve()
  File "/home/bourbouh/Documents/coco-team/cocoSim/tools/verifiers/linux/lib/zustrepy/src/zustre.py", line 180, in encodeAndSolve
    q = self.fp.parse_file (hornFormulas)
  File "src/api/python/z3.py", line 6444, in parse_file
  File "src/api/python/z3core.py", line 4734, in Z3_fixedpoint_from_file
Z3Exception: parser error

[AutoThrottle_Guide_100.txt](https://github.com/coco-team/zustre/files/775031/AutoThrottle_Guide_100.txt)

**Comment by lememta** [comment]
Can you change the code in `generate_tables.py` to output `zsin`, `zcos` and 'ztan' instead of `sin`, `cos` and `tan`.

**Comment by lememta** [comment]
I will close this issue
